### ISSUE TITLE
is this repo used anywhere?

### ISSUE THREAD

**Issue by yuklia** [spryker-sdk/docker-jenkins-boilerplate#11]
I suppose this repo was substituted by https://github.com/spryker/docker-sdk/blob/1.60.0/images/common/services/jenkins/export/Dockerfile , if it is so, lets deprecated or remove this repo at all 

@alexanderM91

**Comment by alexanderM91** [comment]
Hi @yuklia, 
we cannot deprecate or remove the current repository as we use the Jenkins boilerplate image during the Jenkins image build in the https://github.com/spryker/docker-sdk/blob/1.60.0/images/common/services/jenkins/export/Dockerfile#L4
